language: php

php:
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - ./vendor/bin/parallel-lint -e php --exclude vendor .

script:
  - ./vendor/bin/phpunit -v
