language: php

php:
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - ./vendor/bin/parallel-lint -e php --exclude vendor .

script:
  - phpunit tests